### ISSUE TITLE
[RFE] Automatically convert GPL+ modifier to -or-later

### ISSUE THREAD

**Issue by maxice8** [Cogitri/tmplgen#1]
Some licenses specifiy things like `GPL-2.0+`, the + is an indication of `-or-later`.

Would be nice if tmplgen converted it automatically

**Comment by Cogitri** [comment]
Alright, will have to make a fancy list with stuff we want to convert.

**Comment by maxice8** [comment]
On Mon, Nov 26, 2018 at 06:44:21AM -0800, Rasmus Thomsen wrote:
> Alright, will have to make a fancy list with stuff we want to convert.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cogitri/tmplgen/issues/1#issuecomment-441662624

At the current time only converting GPL+ to GPL-or-later would suffice since all GPL-licenses (LGPL, AGPL, GPL) obey this rule.

**Comment by Cogitri** [comment]
Mind giving me an example package for this too?

**Comment by maxice8** [comment]
On Mon, Nov 26, 2018 at 04:02:48PM -0800, Rasmus Thomsen wrote:
> Mind giving me an example package for this too?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cogitri/tmplgen/issues/1#issuecomment-441846941

https://rubygems.org/gems/diff-lcs
