### ISSUE TITLE
prefix rust crate templates with rust- or crate- 

### ISSUE THREAD

**Issue by maxice8** [Cogitri/tmplgen#11]
![image](https://user-images.githubusercontent.com/30738253/49566569-380e7800-f912-11e8-9790-ee85745190af.png)

**Comment by Cogitri** [comment]
Huh, are we really doing that? I see lots of crates that aren't prefixed

**Comment by maxice8** [comment]
On Wed, Dec 05, 2018 at 11:02:50PM -0800, Rasmus Thomsen wrote:
> Huh, are we really doing that? I see lots of crates that aren't prefixed
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cogitri/tmplgen/issues/11#issuecomment-444769525

There is already a conflict with the nix package manager for the nix crate and having a template called libc is screaming for confusion.

**Comment by Cogitri** [comment]
One question though, why exactly do you want to package rust libs?

**Comment by maxice8** [comment]
On Wed, Dec 05, 2018 at 11:50:24PM -0800, Rasmus Thomsen wrote:
> One question though, why exactly do you want to package rust libs?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cogitri/tmplgen/issues/11#issuecomment-444779655

I don't

**Comment by Cogitri** [comment]
Ah, just asking because libc and nix are both libs :)
