### ISSUE TITLE
[RFE] use the sha field of the rubygems API to get the sha256sum for use in checksum.

### ISSUE THREAD

**Issue by maxice8** [Cogitri/tmplgen#3]
The rubygems API provides the .sha key which has the sha256sum of the gem in it's template, it can be used in the checksum= field

**Comment by Cogitri** [comment]
Yes, but neither the crates.io API nor metacpan.org provides that, so I guess it'd be a little more elegant to use run xgensum on the newly generated template?

**Comment by maxice8** [comment]
On Mon, Nov 26, 2018 at 02:40:03AM -0800, Rasmus Thomsen wrote:
> Yes, but neither the crates.io API nor metacpan.org provides that, so I guess it'd be a little more elegant to use run xgensum on the newly generated template?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cogitri/tmplgen/issues/3#issuecomment-441594165

Which is a pain in the ass when using gems because we don't have distfiles= set explicitly in the template which causes it to fail to change checksum=, which means you have to manually do it.

Why should rubygems lose very nice functionality because crates.io and metacpan.org doesn't provide a equivalent ?

**Comment by Cogitri** [comment]
> Which is a pain in the ass when using gems because we don't have distfiles= set explicitly in the template which causes it to fail to change checksum=, which means you have to manually do it.

Ah, right, didn't think about that
