### ISSUE TITLE
Don't set noarch=yes on build_style=gem

### ISSUE THREAD

**Issue by maxice8** [Cogitri/tmplgen#38]
build_style=gem by itself already sets archs=noarch, so it is not necessary to do it in template

**Comment by Cogitri** [comment]
I suppose we should set `arch=noarch` for perl stuff?

**Comment by maxice8** [comment]
On Sun, Feb 24, 2019 at 02:31:58PM -0800, Rasmus Thomsen wrote:
> I suppose we should set `arch=noarch` for perl stuff?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cogitri/tmplgen/issues/38#issuecomment-466824483

yes
