### ISSUE TITLE
[RFE] cut line at 80 columns

### ISSUE THREAD

**Issue by maxice8** [Cogitri/tmplgen#4]
currently depends="" will overflow to over 80 columns if there are many dependencies.

It should cut at 80 columns

**Comment by Cogitri** [comment]
Hum, it should already do that, from helpers.rs:

```
for x in dep_vec {
        let after_string = "".to_string() + &dep_string + x;

        // If the string with the new dep added is longer than or equal to 80
        // chars we want
        if after_string.lines().last().unwrap().len() >= 80 {
            dep_string.push_str("\n")
        }

        dep_string.push_str(x);
        dep_string.push_str(" ");
    }
```

Could you give me an example package for which it doesn't work?

**Comment by maxice8** [comment]
On Mon, Nov 26, 2018 at 02:41:36AM -0800, Rasmus Thomsen wrote:
> Hum, it should already do that, from helpers.rs:
> 
> ```
> for x in dep_vec {
>         let after_string = "".to_string() + &dep_string + x;
> 
>         // If the string with the new dep added is longer than or equal to 80
>         // chars we want
>         if after_string.lines().last().unwrap().len() >= 80 {
>             dep_string.push_str("\n")
>         }
> 
>         dep_string.push_str(x);
>         dep_string.push_str(" ");
>     }
> ```
> 
> Could you give me an example package for which it doesn't work?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cogitri/tmplgen/issues/4#issuecomment-441594639

ruby-rspec

**Comment by Cogitri** [comment]
Ah, didn't consider that {make,host,}depends also have some length
